name: Deploy to AWS

on:
  push:
    branches:
      - develop
      - master

permissions:
  id-token: write # This is required for requesting the JWT to connect Github to AWS
  contents: read  # This is required for actions / checkout

env:
  ENV_NAME: ${{ github.ref == 'refs/heads/develop' && 'development' || 'production' }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Build application files
      run: dotnet publish --no-self-contained --runtime linux-x64 --configuration Release --output ./artifact/publish ./aws-test-app/aws-test-app.csproj

    - name: Install zip functionality
      uses: montudor/action-zip@v1

    - name: Zip up the build application files
      run: zip -qq -r ../publish.zip .
      working-directory: artifact/publish

    - name: Copy Cloudformation template file
      run: cp ./deployment.yml ./artifact/deployment.yml

    - name: Upload build application files
      uses: actions/upload-artifact@v3
      with:
        name: publish
        path: ./artifact

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::604486847222:role/OIDC_GitHub
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: eu-north-1
        
    - name: Delete existing S3 zip files
      run: aws s3 rm s3://ddt-build-files/aws-test-app/${ENV_NAME} --recursive --exclude "*" --include "*.zip"
    
    - name: Upload zip file to S3 bucket
      run: aws s3 cp ./artifact/publish.zip s3://ddt-build-files/aws-test-app/${ENV_NAME}/publish-${{ github.run_number }}.zip
      
    
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:  
    - name: Download build application files
      uses: actions/download-artifact@v3
      with:
        name: publish
        path: artifact

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::604486847222:role/OIDC_GitHub
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: eu-north-1

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: aws-test-app-stack
        template: artifact/deployment.yml
        parameter-overrides: EnvironmentName=${ENV_NAME}, BucketName=ddt-build-files, Key=aws-test-app/production/${{ format('publish-{0}.zip', github.run_number ) }}
        capabilities: CAPABILITY_IAM, CAPABILITY_AUTO_EXPAND
        no-fail-on-empty-changeset: "1"
